spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
    application:
      name: microservicecloud-config-wanghcong-dev
---
spring:
  profiles:
    application:
      name: microservicecloud-config-wanghcong-test
